defmodule Leap.Accounts.Schema.Session do
  @moduledoc "Generated by PowPostgresStore"
  use Ecto.Schema

  @primary_key false
  schema "sessions" do
    field :namespace, :string
    field :key, {:array, :binary}
    field :original_key, :binary
    field :value, :binary
    field :expires_at, :utc_datetime
    timestamps(type: :utc_datetime)
  end
end
