defmodule Leap.Accounts.Schema.User do
  @moduledoc """
  Generated by POW
  Moved to namespace
  """
  use Ecto.Schema
  use Pow.Ecto.Schema

  schema "users" do
    pow_user_fields()

    timestamps()
  end
end
