defmodule Pow.Postgres.Repo.Migrations.CreateTableSessions do
  @moduledoc "Generated by PowPostgresStore"
  use Ecto.Migration

  def change do
    create table(:sessions, primary_key: false) do
      add :namespace, :text
      add :key, {:array, :bytea}
      add :original_key, :bytea
      add :value, :bytea
      add :expires_at, :utc_datetime
      timestamps(type: :utc_datetime)
    end

    create unique_index(:sessions, [:namespace, :original_key])
  end
end
